# Generated by Django 3.2.5 on 2021-07-29 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('urgence', models.CharField(choices=[('UR', 'Urgent'), ('NM', 'Normal'), ('PS', 'Pas Urgent'), ('PU', 'Peu Urgent')], default='NM', max_length=2)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(upload_to='templates/documents/')),
                ('assigner_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nature_courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionnaire.naturescourrier')),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionnaire.organisme')),
                ('type_courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionnaire.typescourrier')),
            ],
        ),
    ]
