# Generated by Django 3.2.5 on 2021-07-29 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaturesCourrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natureName', models.CharField(default='', max_length=255)),
                ('natureCode', models.CharField(default='', max_length=50)),
                ('isActive', models.BooleanField(default=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, default=0)),
                ('alpha2', models.CharField(max_length=2)),
                ('alpha3', models.CharField(max_length=3)),
                ('nom_en_gb', models.CharField(max_length=100)),
                ('nom_fr_fr', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TypesCourrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=255)),
                ('typeCode', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypesOrganisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=255)),
                ('typeCode', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(auto_created=True)),
                ('intitule', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=True)),
                ('isDelete', models.BooleanField(default=False)),
                ('typeOrganisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionnaire.typesorganisme')),
            ],
        ),
    ]
